version: '3.9'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --log-file=- --bind 0.0.0.0:5000 wsgi:APP
    ports:
      - 5000:5000
    env_file:
      - ./.env/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env/.env.db.prod

volumes:
  postgres_data_prod:
